######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 27 14:51:58 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += trivialWizard.cpp
