######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 19 14:37:23 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += testlib

# Input
HEADERS += counter.h counterdisplay.h
SOURCES += counter.cpp counterdisplay.cpp main.cpp
