######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 8 16:55:28 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
