######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 24 11:10:32 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main_window.h
SOURCES += main_window.cpp
RESOURCES += spreadsheet.qrc
