######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 28 16:43:03 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += norwegianwoodstyle.h widgetgallery.h
SOURCES += main.cpp norwegianwoodstyle.cpp widgetgallery.cpp
RESOURCES += styles.qrc
