######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 1 00:33:19 2009
######################################################################

TEMPLATE = app
TARGET = ping
DEPENDPATH += .
INCLUDEPATH += .
QT -= gui
CONFIG += qdbus

# Input
HEADERS += ../ping-common.h
SOURCES += ping.cpp
