######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 6 10:29:45 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
