######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 2 14:24:50 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mysortfilterproxymodel.h window.h
SOURCES += main.cpp mysortfilterproxymodel.cpp window.cpp
