######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 25 18:04:00 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += screenshot.h
SOURCES += main.cpp screenshot.cpp
