######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 25 16:50:52 2008
######################################################################

TEMPLATE = app
TARGET = addressBook 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += addressbook.h
SOURCES += addressbook.cpp main.cpp
