#! /usr/bin/expect

set machine [lindex $argv 0]
spawn console -l wpan -M console.lab.bos.redhat.com $machine 
#expect "Enter wpan@conserver-01.eng.bos.redhat.com's password:"
expect "*.eng.bos.redhat.com's password:"
send "PANWEIPING3\@163\.com\r" 
interact

#jburke-privateswitch.lab.bos.redhat.com
