######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 11 16:31:08 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
