######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 14 17:52:45 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += dbus

# Input
HEADERS += FMDBusConnection.h
SOURCES += FMDBusConnection.cpp main.cpp
