######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 24 14:53:28 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . images
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
RESOURCE += images
