######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 25 15:19:31 2008
######################################################################

TEMPLATE = app
TARGET = widget 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
