######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 30 10:58:00 2010
######################################################################

#QT += network
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lsb

# Input
# HEADERS += ../sb_http.h
SOURCES += main.cpp
