######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 20 11:49:06 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cannonfield.h gameboard.h lcdrange.h
SOURCES += cannonfield.cpp gameboard.cpp lcdrange.cpp main.cpp

TRANSLATIONS = shoot_game_cn.ts 
CODECFORTR = UTF-8
