######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 11 18:01:34 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += renderarea.h window.h
SOURCES += main.cpp renderarea.cpp window.cpp
