######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 23 16:14:59 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += newDialog.h
FORMS += gotoCell.ui
SOURCES += main.cpp newDialog.cpp
