######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 30 20:52:58 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += configdialog.h pages.h
SOURCES += configdialog.cpp main.cpp pages.cpp
RESOURCES += configdialog.qrc
