######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 10:38:04 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp
