######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 2 15:33:04 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
