######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 27 19:35:35 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug

# Input
HEADERS += codeeditor.h
SOURCES += codeeditor.cpp main.cpp
