######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 1 18:01:12 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += regexpdialog.h
SOURCES += main.cpp regexpdialog.cpp
