######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 18 11:50:29 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
