######################################################################
# Automatically generated by qmake (2.01a) Thu Aug 27 03:46:26 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += digitalclock.h
SOURCES += digitalclock.cpp main.cpp
