######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 15:17:50 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp qrc_menus.cpp
