######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 17:39:35 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += coloritem.h robot.h
SOURCES += coloritem.cpp main.cpp robot.cpp
RESOURCES += robot.qrc
