######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 10 15:00:22 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += regext.cpp
