######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 31 14:08:40 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp
