######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 20 16:25:19 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += wizard.h
SOURCES += main.cpp wizard.cpp
