######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 23 16:02:48 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += timer.h
SOURCES += main.cpp timer.cpp
