######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 1 00:33:19 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT -= gui
CONFIG += qdbus

# Input
SOURCES += list_names.cpp
