######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 8 22:48:02 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mouse.h
SOURCES += main.cpp mouse.cpp
RESOURCES += mice.qrc
