######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 2 13:45:10 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += droparea.h dropsitewidget.h
SOURCES += droparea.cpp dropsitewidget.cpp main.cpp
