######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 14 14:44:13 2008
######################################################################

QT += phonon
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
