######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 24 10:17:10 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += xml

# Input
SOURCES += rflocale.cpp
