######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 30 16:44:16 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += licensewizard.h
SOURCES += licensewizard.cpp main.cpp
RESOURCES += licensewizard.qrc
