######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 2 17:44:43 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
