######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 30 17:24:10 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
