######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 29 20:48:11 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += edge.h graphwidget.h node.h
SOURCES += edge.cpp graphwidget.cpp main.cpp node.cpp
