######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 3 15:23:55 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += spinboxdelegate.h stringlistmodel.h
SOURCES += main.cpp spinboxdelegate.cpp stringlistmodel.cpp
