######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 23 17:43:32 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sort_dialog.h
FORMS += sort_dialog.ui
SOURCES += main.cpp sort_dialog.cpp
