######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 1 10:07:32 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tabdialog.h
SOURCES += main.cpp tabdialog.cpp
RESOURCES += tabdialog.qrc
