######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 30 21:52:11 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += delegate.h
SOURCES += delegate.cpp main.cpp
