######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 4 04:43:39 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qdbus

# Input
HEADERS += car.h car_adaptor_p.h
SOURCES += car.cpp car_adaptor.cpp main.cpp
