/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c CarAdaptor -a car_adaptor_p.h:car_adaptor.cpp car.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "car_adaptor_p.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CarAdaptor
 */

CarAdaptor::CarAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CarAdaptor::~CarAdaptor()
{
    // destructor
}

void CarAdaptor::accelerate()
{
    // handle method call com.redflag.carInterface.accelerate
    QMetaObject::invokeMethod(parent(), "accelerate");
}

void CarAdaptor::dccelerate()
{
    // handle method call com.redflag.carInterface.dccelerate
    QMetaObject::invokeMethod(parent(), "dccelerate");
}

void CarAdaptor::turnLeft()
{
    // handle method call com.redflag.carInterface.turnLeft
    QMetaObject::invokeMethod(parent(), "turnLeft");
}

void CarAdaptor::turnRight()
{
    // handle method call com.redflag.carInterface.turnRight
    QMetaObject::invokeMethod(parent(), "turnRight");
}

