/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c CarAdaptor -a car_adaptor_p.h:car_adaptor.cpp car.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CAR_ADAPTOR_P_H_1252010579
#define CAR_ADAPTOR_P_H_1252010579

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.redflag.carInterface
 */
class CarAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.redflag.carInterface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.redflag.carInterface\">\n"
"    <method name=\"accelerate\">\n"
"      <method name=\"dccelerate\">\n"
"        <method name=\"turnLeft\">\n"
"          <method name=\"turnRight\">\n"
"            <signal name=\"crashed\"/>\n"
"          </method>\n"
"        </method>\n"
"      </method>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CarAdaptor(QObject *parent);
    virtual ~CarAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void accelerate();
    void dccelerate();
    void turnLeft();
    void turnRight();
Q_SIGNALS: // SIGNALS
    void crashed();
};

#endif
