######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 17 15:54:16 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
