######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 1 00:33:19 2009
######################################################################

TEMPLATE = app
TARGET = pong
DEPENDPATH += .
INCLUDEPATH += .
QT -= gui
CONFIG += qdbus

# Input
HEADERS += ../ping-common.h pong.h
SOURCES += pong.cpp
