######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 2 17:25:56 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h pieceslist.h puzzlewidget.h
SOURCES += main.cpp mainwindow.cpp pieceslist.cpp puzzlewidget.cpp
RESOURCES += puzzle.qrc
