######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 6 21:20:30 2009
######################################################################

QT += sql
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stringlistmodel.h
SOURCES += main.cpp stringlistmodel.cpp
