######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 11 10:03:48 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += analogclock.h
SOURCES += analogclock.cpp main.cpp
