######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 24 17:33:03 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
