######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 2 16:01:41 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
