######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 25 20:34:20 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
