######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 8 15:42:45 2009
######################################################################
QT += opengl

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += glwidget.h helper.h widget.h window.h
SOURCES += glwidget.cpp helper.cpp main.cpp widget.cpp window.cpp
