######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 31 10:16:55 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
