######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 2 15:24:01 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console

