######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 1 21:38:03 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += colorlisteditor.h window.h
SOURCES += colorlisteditor.cpp main.cpp window.cpp
