######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 29 10:54:40 2010
######################################################################

QT += network
TEMPLATE = lib 
TARGET = sb
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug

# Input
HEADERS += libsb.h \
            sb_http.h
SOURCES += sb_http.cpp

target.path = /usr/lib
sources.files = libsb.h
sources.path  = /usr/include

INSTALLS += target sources 

