######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 29 10:54:40 2010
######################################################################

QT += network
TEMPLATE = app
TARGET =  
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug

# Input
HEADERS += sb_http.h
SOURCES += main.cpp sb_http.cpp
