######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 24 14:47:52 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql

# Input
SOURCES += main.cpp
