######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 1 01:40:26 2009
######################################################################

TEMPLATE = subdirs 
CONFIG += ordered
SUBDIRS = ping pong
