######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 1 17:43:19 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += draglabel.h dragwidget.h
SOURCES += draglabel.cpp dragwidget.cpp main.cpp qrc_draggabelwidget.cpp
RESOURCES += draggabletext.qrc
