######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 14:47:35 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += item.h
SOURCES += item.cpp main.cpp
