######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 6 17:48:28 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
