######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 30 20:57:06 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp
