######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 19 10:04:42 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += struct_write.cpp
