######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 17 14:57:31 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
