######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 31 18:01:08 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
