######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 26 15:13:46 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
