######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 23 10:49:42 2008
######################################################################

TEMPLATE = app
TARGET =helloLayout
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += helloLayout.cpp
