######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 9 14:45:27 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainWindow.h
SOURCES += main.cpp mainWindow.cpp
RESOURCES += application.qrc
